"""Add unique constraint on question_id in answers

Revision ID: 5b506b34ddca
Revises: 2ad2035cf478
Create Date: 2024-09-23 21:24:28.887961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b506b34ddca'
down_revision: Union[str, None] = '2ad2035cf478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_answers_question_id'), 'answers', ['question_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_answers_question_id'), 'answers', type_='unique')
    # ### end Alembic commands ###
