"""Fix constrains

Revision ID: 7fdb3277dbf3
Revises: 5b506b34ddca
Create Date: 2024-09-24 00:09:04.633110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fdb3277dbf3'
down_revision: Union[str, None] = '5b506b34ddca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_question_uc', 'favorites', type_='unique')
    op.create_unique_constraint(op.f('uq_favorites_user_id'), 'favorites', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_favorites_user_id'), 'favorites', type_='unique')
    op.create_unique_constraint('_user_question_uc', 'favorites', ['user_id', 'question_id'])
    # ### end Alembic commands ###
