"""Fix favorites

Revision ID: 3f6a9750513f
Revises: 961a9356094c
Create Date: 2024-09-27 23:51:24.449336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f6a9750513f'
down_revision: Union[str, None] = '961a9356094c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_favorites_user_id', 'favorites', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_favorites_user_id', 'favorites', ['user_id'])
    # ### end Alembic commands ###
