"""Add category slug

Revision ID: dd8b3d09e0d7
Revises: 8465f5cbd55e
Create Date: 2024-09-26 20:38:53.798809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd8b3d09e0d7'
down_revision: Union[str, None] = '8465f5cbd55e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('slug', sa.String(length=20), nullable=False))
    op.create_unique_constraint(op.f('uq_categories_slug'), 'categories', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_categories_slug'), 'categories', type_='unique')
    op.drop_column('categories', 'slug')
    # ### end Alembic commands ###
